name: Jisoo Kim
favicon: null
layout_spectrum: 0.23179941554553807
typography_spectrum: 0.6815236071124673
title: Game Development Generalist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.4531728154979646
  lightness: 0.9796233156230301
  saturation: 0.6176810029428452
  rhythmicContrast: 0.06269003730267286
purpose: []
